version: '3'
services:
    giphyatm:
        tty: True
        stdin_open: True
        image: python:3.5
        volumes:
            - .:/code:cached
        ports:
            - '9000:9000'
        command:
            - /bin/bash
            - -c
            - |
                pip install flask
                pip install requests
                pip install tensorflow==1.12.0
                python /code/flask-start/app.py
